# Generated by Django 4.0.3 on 2022-04-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='super',
            name='alter_ego',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='super',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='super',
            name='primary_ability',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='super',
            name='secondary_ability',
            field=models.CharField(max_length=100),
        ),
    ]
