# Generated by Django 4.0.3 on 2022-04-05 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0005_rename_abilities_super_powers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='power',
            options={'ordering': ['name']},
        ),
    ]
