# Generated by Django 4.0.3 on 2022-04-05 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0007_alter_power_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='power',
            options={'ordering': ['name']},
        ),
    ]
