# Generated by Django 4.0.3 on 2022-04-06 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0009_alter_power_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='super',
            name='alter_ego',
        ),
        migrations.RemoveField(
            model_name='super',
            name='catchphrase',
        ),
        migrations.RemoveField(
            model_name='super',
            name='powers',
        ),
        migrations.RemoveField(
            model_name='super',
            name='super_type',
        ),
    ]
