# Generated by Django 4.0.3 on 2022-04-06 14:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0001_initial'),
        ('supers', '0010_remove_super_alter_ego_remove_super_catchphrase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='super',
            name='alter_ego',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='super',
            name='catchphrase',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='super',
            name='powers',
            field=models.ManyToManyField(to='supers.power'),
        ),
        migrations.AddField(
            model_name='super',
            name='super_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='super_types.super_type'),
            preserve_default=False,
        ),
    ]
