# Generated by Django 4.0.3 on 2022-04-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0011_super_alter_ego_super_catchphrase_super_powers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='power',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='super',
            options={'ordering': ['name']},
        ),
    ]
